# Generated by Django 4.0.4 on 2022-05-05 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Company Name')),
                ('location', models.URLField(verbose_name='URL location')),
                ('open', models.TimeField(verbose_name='ex: 9AM')),
                ('close', models.TimeField(verbose_name='ex: 5PM')),
                ('website_address', models.URLField(verbose_name='website URL')),
                ('company_status', models.CharField(choices=[('local', 'Local company'), ('international', 'International company'), ('unknown', 'Unknown')], default='unknown', max_length=35)),
            ],
        ),
    ]
