# Generated by Django 4.0.4 on 2022-05-05 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='close',
            field=models.TimeField(verbose_name='ex: (18:00:00)'),
        ),
        migrations.AlterField(
            model_name='company',
            name='open',
            field=models.TimeField(verbose_name='ex: (10:00:00)'),
        ),
    ]
